packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - nestjs-pino
  - prisma
  - sharp
